name: build-bionic

on:
  push:
    branches:
      - master
      - photobooth-docker
  pull_request:
    branches:
      - master
      - photobooth-docker
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.repository == 'andi34/live-custom-ubuntu-from-scratch'

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd scripts
          sed -i -E 's/TARGET_UBUNTU_VERSION=(.*)/TARGET_UBUNTU_VERSION="bionic"/g' config.sh
          ./build.sh -
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: photobooth-bionic
          path: |
            scripts/photobooth.iso
            scripts/image/md5sum.txt
